.ALIASES
V_V1            V1(+=N01245 -=0 ) CN @B5.SCHEMATIC1(sch_1):INS1279@SOURCE.VDC.Normal(chips)
L_L1            L1(1=N01363 2=0 ) CN @B5.SCHEMATIC1(sch_1):INS1383@ANALOG.L.Normal(chips)
X_S1            S1(1=N01245 2=N01263 ) CN @B5.SCHEMATIC1(sch_1):INS1221@EVAL.Sw_tClose.Normal(chips)
R_R2            R2(1=N01369 2=N01263 ) CN @B5.SCHEMATIC1(sch_1):INS1319@ANALOG.R.Normal(chips)
V_V2            V2(+=N01369 -=0 ) CN @B5.SCHEMATIC1(sch_1):INS1401@SOURCE.VDC.Normal(chips)
R_R3            R3(1=N01363 2=N01263 ) CN @B5.SCHEMATIC1(sch_1):INS1299@ANALOG.R.Normal(chips)
R_R1            R1(1=0 2=N01245 ) CN @B5.SCHEMATIC1(sch_1):INS1341@ANALOG.R.Normal(chips)
.ENDALIASES
